id: P009230
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:29:06.468588
source_metadata:
  id: bdr:W8LS18751
  title: གཉེན་སྒྲིག་དང་ཁྱིམ་ཚང་སྐོར་གྱི་བཅའ་ཁྲིམས་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  author: ''
  volumes:
    e106cd1400344c5c849f5acdf4437af5:
      image_group_id: I8LS18753
      title: ''
      volume_number: 1
      total_pages: 206
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
