id: IEA88B238
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:51:16+00:00'
last_modified: '2022-06-08T09:32:31.399830+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18751
  title: གཉེན་སྒྲིག་དང་ཁྱིམ་ཚང་སྐོར་གྱི་བཅའ་ཁྲིམས་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    14E1:
      image_group_id: I8LS18753
      title: ''
      total_pages: 206
      order: 1
      base_file: 14E1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
